USE [master]
GO

/****** Object:  Database [FBDb]    Script Date: 17-03-2020 12:19:16 ******/
CREATE DATABASE [FBDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FBDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\FBDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FBDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\FBDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FBDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FBDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FBDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FBDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FBDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FBDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [FBDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FBDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FBDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FBDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FBDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FBDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FBDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FBDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FBDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FBDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FBDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FBDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FBDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FBDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FBDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FBDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FBDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FBDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FBDb] SET  MULTI_USER 
GO

ALTER DATABASE [FBDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FBDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FBDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FBDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FBDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FBDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FBDb] SET  READ_WRITE 
GO

